services:
  db:
    container_name: Youvento_Laravel
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: Youvento_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container_v3
    image: dpage/pgadmin4:9.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root_password
    ports:
      - "8083:80"

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_container
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "83:80"

volumes:
  db_data: